<?php

namespace App\Service;

use Sip\ReaderManager\FileStorage as SipFileStorage;

class FileStorage extends SipFileStorage
{
    protected string $storagePath =  __DIR__.'/../../var/';

    public function isUrlLoaded(string $url): bool
    {
        return parent::isUrlLoaded($url); // TODO: Change the autogenerated stub
    }
}
