<?php

namespace App\Service;

use Sip\ReaderManager\AbstractStorage;

class MemcachedStorage extends AbstractStorage
{
    private \Memcached $memcached;
    public string $savedLengthKey = 'length';
    public string $currentDeepKey = 'deep';
    public string $urlsKey = 'list';
    
    public function __construct(string $name)
    {
        $this->savedLengthKey .= $name;
        $this->currentDeepKey .= $name;
        $this->urlsKey .= $name;
        
        $this->memcached = new \Memcached();
        $this->memcached->addServer('memcached', 11211);

        $this->currentDeep = (int)$this->memcached->get($this->currentDeepKey);
        $this->savedLength = (int)$this->memcached->get($this->savedLengthKey);
        if ($urls = $this->memcached->get($this->urlsKey)) {
            $this->urls = $urls;
        }
    }

    public function addUrls(string $url, array $urlData = []): self
    {
        if (count($this->urls) >= 50) {
            $this->urls = [];
        }
        return parent::addUrls($url, $urlData); // TODO: Change the autogenerated stub
    }

    public function save(): self
    {
        $this->memcached->set($this->urlsKey, $this->urls);
        $this->memcached->set($this->savedLengthKey, $this->savedLength);
        $this->memcached->set($this->currentDeepKey, $this->currentDeep);
        return $this;
    }
}

